AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  IndexLF1new:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: IndexLF1new
      Handler: Upload.my_handler
      Runtime: python3.8
      CodeUri: ./
      Description: ''
      MemorySize: 128
      Timeout: 60
      Role: 'arn:aws:iam::436831233028:role/LambdaRole'
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket1
            Events:
              - 's3:ObjectCreated:Put'

  SearchLF2new:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: SearchLF2new
      Handler: Search.lambda_handler
      Runtime: python3.8
      CodeUri: ./
      Description: ''
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::436831233028:role/LambdaRole'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /search
            Method: GET
  Bucket1:
    Type: 'AWS::S3::Bucket'
